# Generated by Django 5.1.14 on 2025-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the card type (e.g., Visa, Mastercard)', max_length=50)),
                ('logo_image', models.ImageField(help_text='Image file for the card logo', upload_to='card_logos/')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display the logos')),
                ('is_active', models.BooleanField(default=True, help_text='Whether to display this logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Card Logo',
                'verbose_name_plural': 'Card Logos',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The main title/headline for the home page', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle or tagline for the home page')),
                ('description', models.TextField(help_text='Main description of the X-Crewter service')),
                ('call_to_action_text', models.CharField(help_text='Text for the main call-to-action button', max_length=100)),
                ('pricing_info', models.TextField(help_text='Information about pricing plans')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Content',
                'verbose_name_plural': 'Home Page Content',
            },
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the legal page', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier for the page', unique=True)),
                ('content', models.TextField(help_text='Full content of the legal page')),
                ('page_type', models.CharField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms and Conditions'), ('refund', 'Refund Policy'), ('contact', 'Contact Information')], help_text='Type of legal page', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the page is currently published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(help_text="Key for the setting (e.g., 'currency_display', 'contact_email')", max_length=100, unique=True)),
                ('setting_value', models.TextField(help_text='Value of the setting')),
                ('description', models.TextField(help_text='Description of what this setting controls')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
