# Generated by Django 5.1.14 on 2025-12-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardlogo',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Image file for the card logo', null=True, upload_to='card_logos/'),
        ),
    ]
