# Generated by Django 5.2.9 on 2026-01-29 15:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonScreeningQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(unique=True)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('YES_NO', 'Yes/No'), ('CHOICE', 'Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILE_UPLOAD', 'File Upload')], max_length=20)),
                ('category', models.CharField(default='General', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=3000)),
                ('required_skills', models.JSONField()),
                ('required_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('job_level', models.CharField(choices=[('Intern', 'Intern'), ('Entry', 'Entry'), ('Junior', 'Junior'), ('Senior', 'Senior')], max_length=10)),
                ('start_date', models.DateTimeField()),
                ('expiration_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=10)),
                ('application_link', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('YES_NO', 'Yes/No'), ('CHOICE', 'Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('FILE_UPLOAD', 'File Upload')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_questions', to='jobs.joblisting')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['status'], name='jobs_joblis_status_29e1b0_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['start_date'], name='jobs_joblis_start_d_28d8ff_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['expiration_date'], name='jobs_joblis_expirat_ff81d5_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['status', 'start_date', 'expiration_date'], name='jobs_joblis_status_40b957_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['created_at'], name='jobs_joblis_created_7f6d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningquestion',
            index=models.Index(fields=['job_listing'], name='jobs_screen_job_lis_2b3d55_idx'),
        ),
        migrations.AddIndex(
            model_name='screeningquestion',
            index=models.Index(fields=['order'], name='jobs_screen_order_1e3ae2_idx'),
        ),
    ]
