# Generated by Django 5.2.9 on 2026-02-20 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='description',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='modification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
