# Generated by Django 5.2.9 on 2026-03-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joblisting_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='analysis_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
