# Generated by Django 5.2.9 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_analysis_in_progress_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='batch_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='total_resumes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='upload_type',
            field=models.CharField(
                choices=[('form', 'Form Resume Upload'), ('bulk', 'Bulk Resume Upload')],
                default='form',
                help_text='Type of resume upload method for this job listing',
                max_length=10
            ),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(
                check=models.Q(('batch_count__lte', 3)),
                name='batch_count_max_3'
            ),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(
                check=models.Q(('total_resumes__lte', 300)),
                name='total_resumes_max_300'
            ),
        ),
    ]
