# Generated by Django 5.2.9 on 2026-03-02 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('applications', '0007_auto_20260222_2228'),
        ('jobs', '0002_alter_joblisting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisresult',
            name='applicant',
            field=models.ForeignKey(help_text='Applicant this analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='applications.applicant'),
        ),
        migrations.AddConstraint(
            model_name='aianalysisresult',
            constraint=models.UniqueConstraint(fields=('applicant', 'job_listing'), name='unique_analysis_per_applicant_per_job'),
        ),
    ]
