# Generated by Django 5.2.9 on 2026-03-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_aianalysisresult_education_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisresult',
            name='category',
            field=models.CharField(blank=True, choices=[('Best Match', 'Best Match'), ('Good Match', 'Good Match'), ('Partial Match', 'Partial Match'), ('Mismatched', 'Mismatched'), ('Unprocessed', 'Unprocessed')], default=None, help_text='Match category based on overall score', max_length=20, null=True),
        ),
    ]
