# Generated by Django 5.2.9 on 2026-02-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted')], default='submitted', editable=False, max_length=20),
        ),
    ]
