# Generated by Django 5.2.9 on 2026-02-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_applicant_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicant',
            name='application_email_7d8a88_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='application_phone_e40c55_idx',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='application_resume__ffae5b_idx',
        ),
    ]
