# Generated by Django 5.2.9 on 2026-02-22 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_applicant_application_email_7d8a88_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='reference_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
