# Generated by Django 5.2.9 on 2026-02-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicant_reference_number'),
    ]

    operations = [
        # First ensure all existing records have a reference_number
        migrations.RunPython(
            code=lambda apps, schema_editor: backfill_reference_numbers(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        # Now alter the field to remove null=True
        migrations.AlterField(
            model_name='applicant',
            name='reference_number',
            field=models.CharField(
                max_length=20,
                unique=True,
                editable=False,
                db_index=True
            ),
        ),
    ]


def backfill_reference_numbers(apps):
    """
    Populate missing Applicant.reference_number values for existing Applicant records.
    
    For each Applicant whose reference_number is null, generate a unique reference number and persist it to the database.
    
    Parameters:
        apps: The migration apps registry used to retrieve the historical Applicant model.
    """
    from apps.applications.models import generate_reference_number
    Applicant = apps.get_model('applications', 'Applicant')
    seen = set()
    for applicant in Applicant.objects.filter(reference_number__isnull=True):
        # Generate unique reference number
        while True:
            ref = generate_reference_number()
            if ref not in seen and not Applicant.objects.filter(reference_number=ref).exists():
                break
        seen.add(ref)
        applicant.reference_number = ref
        applicant.save(update_fields=['reference_number'])
