# Generated by Django 5.2.9 on 2026-02-22 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicant_access_token'),
    ]

    operations = [
        # Backfill any remaining NULL access_tokens
        migrations.RunPython(
            code=lambda apps, schema_editor: backfill_access_tokens(apps),
            reverse_code=migrations.RunPython.noop,
        ),
        # Now alter the field to remove null=True
        migrations.AlterField(
            model_name='applicant',
            name='access_token',
            field=models.UUIDField(
                unique=True,
                editable=False,
                db_index=True,
                help_text="Secure token for accessing application success page"
            ),
        ),
    ]


def backfill_access_tokens(apps):
    """
    Populate missing Applicant access tokens by assigning a new UUID4 to each applicant whose `access_token` is null.
    
    Parameters:
        apps (django.apps.registry.Apps): Historical apps registry provided to migration functions; used to retrieve the `Applicant` model.
    """
    Applicant = apps.get_model('applications', 'Applicant')
    for applicant in Applicant.objects.filter(access_token__isnull=True):
        applicant.access_token = uuid.uuid4()
        applicant.save(update_fields=['access_token'])
