# Generated by Django 5.2.9 on 2026-03-23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_create_uploadbatch_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='upload_batch',
            field=models.ForeignKey(
                blank=True,
                help_text='Source upload batch (null for form submissions)',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='applicants',
                to='applications.uploadbatch'
            ),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['upload_batch'], name='applications_upload_batch_idx'),
        ),
    ]
