# Generated by Django 5.2.9 on 2026-04-01 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20260401_1906'),
    ]

    operations = [
        # Remove the unique_phone_per_job constraint
        # Multiple applicants can now share the same phone number (e.g., couples, roommates)
        # Duplicate detection is handled at the validation stage, not database level
        migrations.RemoveConstraint(
            model_name='applicant',
            name='unique_phone_per_job',
        ),
    ]
