# Generated by Django 5.2.9 on 2026-04-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_remove_uploadbatch_file_count_max_100_and_more'),
    ]

    operations = [
        # Restore file_count_max_100 constraint that was accidentally removed
        migrations.AddConstraint(
            model_name='uploadbatch',
            constraint=models.CheckConstraint(
                check=models.Q(('file_count__lte', 100)),
                name='file_count_max_100'
            ),
        ),
    ]
