# Generated by Django 5.2.9 on 2026-04-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_auto_20260401_2131'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadbatch',
            name='file_count_max_100',
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='commit_summary',
            field=models.JSONField(blank=True, help_text='Final commit results: {applicants_created, files_failed, errors}', null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='processing_progress',
            field=models.JSONField(default=dict, help_text='Processing progress: {total, processed, failed, current_file, status}'),
        ),
        migrations.AddField(
            model_name='uploadbatch',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('validating', 'Validating'), ('awaiting_review', 'Awaiting Review'), ('processing', 'Processing'), ('committed', 'Committed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
