# Generated by Django 5.2.9 on 2026-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_add_async_processing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='processing_task_id',
            field=models.CharField(blank=True, default='', help_text='Celery task ID for the processing task', max_length=255),
        ),
    ]
