# Generated by Django 5.2.9 on 2026-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_add_processing_task_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadbatch',
            name='child_task_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of Celery task IDs for child tasks (process_resume_async)'),
        ),
    ]
