# Generated by Django 5.2.9 on 2026-02-28 00:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0007_auto_20260222_2228'),
        ('jobs', '0002_alter_joblisting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for analysis result', primary_key=True, serialize=False)),
                ('education_score', models.IntegerField(help_text='Education metric score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_score', models.IntegerField(help_text='Skills metric score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('experience_score', models.IntegerField(help_text='Experience metric score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('supplemental_score', models.IntegerField(default=0, help_text='Supplemental information score (0-100) - tracked separately, not included in overall score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('overall_score', models.IntegerField(help_text='Weighted overall score (Experience 50%, Skills 30%, Education 20%), floored to integer', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('category', models.CharField(choices=[('Best Match', 'Best Match'), ('Good Match', 'Good Match'), ('Partial Match', 'Partial Match'), ('Mismatched', 'Mismatched'), ('Unprocessed', 'Unprocessed')], help_text='Match category based on overall score', max_length=20)),
                ('education_justification', models.TextField(blank=True, help_text='Justification for education score')),
                ('skills_justification', models.TextField(blank=True, help_text='Justification for skills score')),
                ('experience_justification', models.TextField(blank=True, help_text='Justification for experience score')),
                ('supplemental_justification', models.TextField(blank=True, help_text='Justification for supplemental information score')),
                ('overall_justification', models.TextField(blank=True, help_text='Overall justification for category assignment')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Analyzed', 'Analyzed'), ('Unprocessed', 'Unprocessed')], default='Pending', help_text='Analysis status: Pending, Analyzed, or Unprocessed', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if analysis failed (truncated to 1000 chars)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the analysis result was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the analysis result was last updated')),
                ('analysis_started_at', models.DateTimeField(blank=True, help_text='When analysis processing started for this applicant', null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, help_text='When analysis processing completed for this applicant', null=True)),
                ('applicant', models.OneToOneField(help_text='Applicant this analysis belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_result', to='applications.applicant')),
                ('job_listing', models.ForeignKey(help_text='Job listing associated with this analysis', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis_results', to='jobs.joblisting')),
            ],
            options={
                'db_table': 'analysis_ai_analysis_result',
                'ordering': ['-overall_score'],
                'indexes': [models.Index(fields=['job_listing', 'category'], name='analysis_ai_job_lis_8c9e64_idx'), models.Index(fields=['job_listing', 'status'], name='analysis_ai_job_lis_94ff21_idx'), models.Index(fields=['job_listing', 'overall_score'], name='analysis_ai_job_lis_3524f0_idx'), models.Index(fields=['status'], name='analysis_ai_status_c063e4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['Best Match', 'Good Match', 'Partial Match', 'Mismatched']), ('status', 'Analyzed')), models.Q(('category', 'Unprocessed'), ('status', 'Unprocessed')), ('status', 'Pending'), _connector='OR'), name='category_status_consistency')],
            },
        ),
    ]
