# Generated by Django 5.2.9 on 2026-03-02 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_aianalysisresult_applicant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisresult',
            name='education_score',
            field=models.IntegerField(blank=True, help_text='Education metric score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='experience_score',
            field=models.IntegerField(blank=True, help_text='Experience metric score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='overall_score',
            field=models.IntegerField(blank=True, help_text='Weighted overall score (Experience 50%, Skills 30%, Education 20%), floored to integer', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='skills_score',
            field=models.IntegerField(blank=True, help_text='Skills metric score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='aianalysisresult',
            name='supplemental_score',
            field=models.IntegerField(blank=True, default=None, help_text='Supplemental information score (0-100) - tracked separately, not included in overall score', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
