openapi: 3.0.0
info:
  title: Remember Me Functionality API
  version: 1.0.0
  description: API extensions for Remember Me functionality

paths:
  /api/accounts/auth/login/:
    post:
      summary: User login with optional Remember Me functionality
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Username or email address
                password:
                  type: string
                  description: User password
                remember_me:
                  type: boolean
                  description: Whether to enable extended session (Remember Me)
                  default: false
              required:
                - username
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: '#/components/schemas/User'
                  redirect_url:
                    type: string
                    description: URL to redirect user after login
        '400':
          description: Invalid credentials or request data
          content:
            application/json:
              schema:
                type: object
                properties:
                  non_field_errors:
                    type: array
                    items:
                      type: string
        '401':
          description: Unauthorized access

  /api/accounts/auth/refresh/:
    post:
      summary: Refresh authentication tokens
      description: Refresh tokens for both standard and Remember Me sessions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh:
                  type: string
                  description: Refresh token
      responses:
        '200':
          description: Tokens successfully refreshed
          content:
            application/json:
              schema:
                type: object
                properties:
                  access:
                    type: string
                    description: New access token
        '400':
          description: Invalid refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
        '401':
          description: Unauthorized access

  /api/accounts/auth/logout/:
    post:
      summary: User logout
      description: Logout user and invalidate all active Remember Me sessions
      responses:
        '204':
          description: Successfully logged out
        '400':
          description: Logout failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: User ID
        username:
          type: string
          description: Username
        email:
          type: string
          description: User email address
        first_name:
          type: string
          description: User's first name
        last_name:
          type: string
          description: User's last name
        date_joined:
          type: string
          format: date-time
          description: When the user joined
        profile:
          $ref: '#/components/schemas/UserProfile'
    
    UserProfile:
      type: object
      properties:
        subscription_status:
          type: string
          description: Current subscription status
        subscription_end_date:
          type: string
          format: date-time
          description: When subscription ends
        chosen_subscription_plan:
          type: string
          description: Selected subscription plan
        is_talent_acquisition_specialist:
          type: boolean
          description: Whether user is a talent acquisition specialist
        created_at:
          type: string
          format: date-time
          description: When profile was created
        updated_at:
          type: string
          format: date-time
          description: When profile was last updated