# Generated by Django 5.2.9 on 2026-03-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_add_upload_type_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='joblisting',
            name='batch_count_max_3',
        ),
        migrations.RemoveConstraint(
            model_name='joblisting',
            name='total_resumes_max_300',
        ),
    ]
