# Generated by Django 5.2.9 on 2026-02-20 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_alter_joblisting_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('resume_file', models.FileField(max_length=500, upload_to='applications/resumes/')),
                ('resume_file_hash', models.CharField(db_index=True, max_length=64)),
                ('resume_parsed_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='submitted', max_length=20)),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.applicant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='jobs.screeningquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['job_listing', 'submitted_at'], name='application_job_lis_22a406_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['email'], name='application_email_7d8a88_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['phone'], name='application_phone_e40c55_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['resume_file_hash'], name='application_resume__ffae5b_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('job_listing', 'resume_file_hash'), name='unique_resume_per_job'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('job_listing', 'email'), name='unique_email_per_job'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('job_listing', 'phone'), name='unique_phone_per_job'),
        ),
        migrations.AddIndex(
            model_name='applicationanswer',
            index=models.Index(fields=['applicant', 'question'], name='application_applica_48ea0b_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationanswer',
            constraint=models.UniqueConstraint(fields=('applicant', 'question'), name='unique_answer_per_question'),
        ),
    ]
