# Generated by Django 5.2.9 on 2026-02-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20260222_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='access_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Secure token for accessing application success page', null=True, unique=True),
        ),
    ]
