# Generated by Django 5.2.9 on 2026-03-23

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auto_20260222_2228'),
        ('jobs', '0004_add_upload_type_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('batch_number', models.PositiveIntegerField(help_text='Sequential batch number (1, 2, or 3)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('uploading', 'Uploading'),
                        ('validating', 'Validating'),
                        ('awaiting_review', 'Awaiting Review'),
                        ('committed', 'Committed'),
                        ('cancelled', 'Cancelled'),
                        ('failed', 'Failed'),
                    ],
                    default='pending',
                    max_length=20
                )),
                ('temp_files', models.JSONField(
                    default=list,
                    help_text='List of temporary file metadata: [{file_id, filename, file_hash, size, status}]'
                )),
                ('duplicate_summary', models.JSONField(
                    blank=True,
                    help_text='Duplicate detection results: {duplicates: [...], actions: {...}}',
                    null=True
                )),
                ('job_listing', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='upload_batches',
                    to='jobs.joblisting'
                )),
                ('uploaded_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='upload_batches',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'ordering': ['batch_number'],
                'indexes': [
                    models.Index(fields=['job_listing', 'batch_number'], name='applications_job_batch_idx'),
                    models.Index(fields=['status'], name='applications_ub_status_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='uploadbatch',
            constraint=models.CheckConstraint(
                check=models.Q(('batch_number__lte', 3)),
                name='batch_number_max_3'
            ),
        ),
        migrations.AddConstraint(
            model_name='uploadbatch',
            constraint=models.CheckConstraint(
                check=models.Q(('file_count__lte', 100)),
                name='file_count_max_100'
            ),
        ),
    ]
