# Generated by Django 5.2.9 on 2026-04-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_add_upload_batch_field'),
    ]

    operations = [
        # Remove the batch_number_max_3 constraint to allow more than 3 batches
        # (users can upload multiple times until 300 resumes is reached)
        migrations.RemoveConstraint(
            model_name='uploadbatch',
            name='batch_number_max_3',
        ),
    ]
