# Generated by Django 5.2.9 on 2026-04-01 19:23

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_auto_20260401_2037'),
        ('jobs', '0005_remove_joblisting_batch_count_max_3_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='uploadbatch',
            name='file_count_max_100',
        ),
        migrations.RemoveIndex(
            model_name='applicant',
            name='applications_upload_batch_idx',
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone_extraction_failed',
            field=models.BooleanField(default=False, help_text='True if phone number extraction from resume failed'),
        ),
        migrations.AlterField(
            model_name='uploadbatch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='uploadbatch',
            constraint=models.UniqueConstraint(fields=('job_listing', 'batch_number'), name='unique_batch_per_job_listing'),
        ),
    ]
